version: v1

labels:
  - label: 'bug'
    matcher:
      title: "^bug(\\([^()\\r\\n]*\\))?:.*"
      body: "(\\n|.)*- \\[x\\] bug(\\n|.)*"

  - label: 'feat'
    matcher:
      title: "^feat(\\([^()\\r\\n]*\\))?:.*"
      body: "(\\n|.)*- \\[x\\] feat(\\n|.)*"

  - label: 'docs'
    matcher:
      title: "^(docs|doc)(\\([^()\\r\\n]*\\))?:.*"

  - label: 'perf'
    matcher:
      title: "^perf(\\([^()\\r\\n]*\\))?:.*"
