repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: mise run lint
        language: python
        types: [ fish ]
        require_serial: true

  - repo: local
    hooks:
      - id: validate-commit-msg
        name: Validate commit message
        entry: cog verify --file
        language: system
        stages: [ commit-msg ]
