tag_prefix = "v"
branch_whitelist = ["main"]
ignore_merge_commits = true
pre_bump_hooks = [
  "git config user.name 'github-actions[bot]'",
  "git config user.email 'github-actions[bot]@users.noreply.github.com'",
]
post_bump_hooks = [
  "git push",
  "git push origin {{version_tag}}",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "gazorby"
repository = "fifc"

[commit_types]
feat = { changelog_title = "🚀 Features" }
fix = { changelog_title = "🐛 Bug Fixes" }
docs = { changelog_title = "📚 Documentation" }
perf = { changelog_title = "⚡ Performance" }
refactor = { changelog_title = "🚜 Refactor" }
style = { changelog_title = "🎨 Styling" }
test = { changelog_title = "🧪 Testing" }
build = { changelog_title = "⚙️ Miscellaneous Tasks" }
ci = { changelog_title = "⚙️ Miscellaneous Tasks" }
revert = { changelog_title = "◀️ Revert" }
chore = { omit_from_changelog = true }
