tag_prefix = "v"
branch_whitelist = ["main"]
ignore_merge_commits = true
# Use a non-native marker (not one of GitHub's [skip ci]/[ci skip]/... strings)
# so we can do our own skip logic in workflow
skip_ci = "[ci-skip]"
post_bump_hooks = [
    "git push",
    "git push origin {{version_tag}}",
]

[changelog]
path = "CHANGELOG.md"
template = ".github/changelog.tera"
remote = "github.com"
owner = "gazorby"
repository = "fifc"

authors = [
    { signature = "gazorby", username = "gazorby" },
    { signature = "Matthieu", username = "gazorby" }
]

[commit_types]
feat = { changelog_title = "🚀 Features", order = 1 }
fix = { changelog_title = "🐛 Bug Fixes", order = 2 }
perf = { changelog_title = "⚡ Performance", order = 3 }
refactor = { changelog_title = "🚜 Refactor", order = 4 }
ref = { changelog_title = "🚜 Refactor", order = 4 }
revert = { changelog_title = "◀️ Revert", order = 5 }
docs = { changelog_title = "📚 Documentation", order = 6 }
build = { changelog_title = "⚙️ Miscellaneous Tasks", order = 7 }
ci = { changelog_title = "⚙️ Miscellaneous Tasks", order = 7 }
style = { changelog_title = "🎨 Styling", order = 8 }

chore = { omit_from_changelog = true }
test = { omit_from_changelog = true }

[bump_profiles.manual]
pre_bump_hooks = [
    "mise run lint",
]

post_bump_hooks = [
    "echo 'Manual bump from {{latest}} to {{version}}.'"
]
