name: ⏫ Bump the version

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "What kind of release is this?"
        required: false
        default: "auto"
        type: choice
        options:
          - "auto"
          - "major"
          - "minor"
          - "patch"

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Bump version and changelog
        uses: cocogitto/cocogitto-action@390bda87a19bf627e03ad075c67a11e9ddbb7547 # v4
        with:
          command: bump
          args: ${{ github.event.inputs.releaseType == 'auto' && '--auto' || format('--{0}', github.event.inputs.releaseType) }}
