name: 🚀 Continuous Deployment

env:
  GIT_USERNAME: github-actions[bot]

on:
  workflow_dispatch:

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          persist-credentials: 'false'

      - name: Generate documentation changelog
        uses: orhun/git-cliff-action@e16f179f0be49ecdfe63753837f20b9531642772 # v4
        id: git-cliff-repo
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate release changelog
        uses: orhun/git-cliff-action@e16f179f0be49ecdfe63753837f20b9531642772 # v4
        id: git-cliff-release
        with:
          config: cliff.toml
          args: --verbose --latest --strip header
        env:
          OUTPUT: RELEASE_CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit
        run: |
          git checkout main
          git config user.name '${{ env.GIT_USERNAME }}'
          git config user.email '${{ env.GIT_USERNAME }}@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "build(doc) update changelog"
          git push https://${{ env.GIT_USERNAME }}:${{ secrets.PAT }}@github.com/${GITHUB_REPOSITORY}.git main

      - name: Upload release notes
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: release-notes
          path: RELEASE_CHANGELOG.md

  release:
    name: Create GitHub release
    needs: changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          persist-credentials: 'false'

      - name: Download release notes
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: release-notes

      - name: Create GitHub release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3
        with:
          body_path: RELEASE_CHANGELOG.md
          token: ${{ secrets.PAT }}
