name: 🔂 Continuous Integration

on:
  push:
    branches: [main, ci/*, dependabot/*, renovate/*]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]

  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: 🔬 ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup mise
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4
        with:
          cache: true
          log_level: debug

      - name: Install Fish
        uses: fish-actions/install-fish@v1.1.0

      - name: Install abbreviation-tips with fisher
        uses: fish-shop/install-plugin@1ca93fe158b1ad8251835d4e310f99a3ec1f3d86 # v2
        with:
          plugin-manager: fisher
          plugins: gazorby/fifc

      - name: Run Fishtape tests
        uses: fish-shop/run-fishtape-tests@v1
        with:
          pattern: tests/**.fish
        # timeout in case tests get stuck on fzf
        timeout-minutes: 3

  lint:
    name: ✨ Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup mise
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4
        with:
          cache: true
          log_level: debug

      - name: Install Fish
        uses: fish-actions/install-fish@v1.1.0

      - name: Run linting
        run: mise run lint
